version: '3.8'
services:
  web:
    build: .
    container_name: apf-python
    ports:
     - "5000:5000"
    volumes:
     - ./project-container:/project-container
    environment:
     - NAME=World
